def fib():                     # Define a generator function for Fibonacci numbers
    a, b = 0, 1                 # Initialize first two numbers of the sequence
    while True:                 # Infinite loop to keep generating numbers
        yield a                 # Yield the current number and pause
        a, b = b, a+b           # Update values for the next Fibonacci number

for f in fib():                 # Iterate through numbers generated by fib()
    if f > 100:                 # Stop if the number exceeds 100
        break                   # Exit the loop
    print(f)                    # Print the current Fibonacci number

"""
This code defines a generator function `fib()` that yields Fibonacci numbers indefinitely. 
The `for` loop consumes values from the generator, printing them one by one, 
and stops when a number greater than 100 is reached.
"""

# PRACTICE EXERCISE
def square():
    n = 1
    while True:
        yield n * n
        n += 1

for g in square():
    if g > 100:
        break
    print(g)